version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - VITE_API_URI=http://localhost:3018/v1/
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3018:3018"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
